const mongoose = require("mongoose")

const NoteSchema = new mongoose.Schema({
    title:{
        type:"String",
        require:true
    },
    description:{
        type:"String",
        require:true
    },
    status:{
        type:"String",
        require:true
    },
    userId:{
        type: mongoose.Schema.Types.ObjectId, ref:"User", required:true   //in this the type of the id is mongoose id which has been automatically generated by mongoose schema.
    }
    
},
{
    versionKey:false,
    timestamps:true
});


const NoteModel = mongoose.model("note", NoteSchema);
module.exports = NoteModel